// Reusable short-form creative systems. These are structural templates, not copies of any reference.
export const shortTemplateCatalog = [
  { id: "yapper-vsl-educator", name: "Yapper VSL Educator", purpose: "A direct-to-camera, curiosity-led short with three proof-safe beats and fast cutaway support.", flow: ["first-frame hook", "re-hook / contrast", "three reasons or questions", "process proof cue", "soft CTA + disclosure"], channels: ["Instagram Reels", "TikTok", "YouTube Shorts", "Facebook Reels"], useCases: ["knee", "cardiac", "dental", "fertility", "oncology", "all"] },
  { id: "decision-escalation", name: "Decision Escalation", purpose: "An original cinematic 3D scenario that builds decision friction, then resolves into a safe comparison checklist.", flow: ["you-in-the-scenario hook", "records mismatch", "comparison mismatch", "coordination pressure", "comparison-brief turn", "scope-safe CTA"], channels: ["Instagram Reels", "TikTok", "YouTube Shorts"], useCases: ["knee", "cardiac", "dental", "all"] },
  { id: "song-checklist", name: "Song Checklist", purpose: "An audio-first mnemonic short: one original master track, locked scene slices, and beat-matched A-roll/B-roll.", flow: ["sung hook", "records beat", "written-brief beat", "coordinator beat", "comparison turn", "disclosure CTA"], channels: ["Instagram Reels", "TikTok", "YouTube Shorts"], useCases: ["knee", "cardiac", "dental", "all"] },
  { id: "doctor-explainer", name: "Doctor Explainer", purpose: "Teach one practical question with a fictional or verified presenter.", flow: ["question hook", "one insight", "three teaching beats", "takeaway", "disclaimer"], channels: ["Instagram", "TikTok", "YouTube Shorts", "Facebook"], useCases: ["knee", "cardiac", "dental", "fertility", "oncology"] },
  { id: "myth-vs-fact", name: "Myth vs Fact", purpose: "Correct a common misunderstanding without diagnosing or promising an outcome.", flow: ["myth", "fact boundary", "what to verify", "safe next step"], channels: ["Instagram", "TikTok", "YouTube Shorts", "Pinterest"], useCases: ["all"] },
  { id: "three-questions", name: "Three Questions", purpose: "Turn an intimidating medical-travel decision into a clear checklist.", flow: ["pain-point hook", "question one", "question two", "question three", "CTA"], channels: ["Organic", "Paid", "SEO embed"], useCases: ["all"] },
  { id: "patient-journey", name: "Patient Journey Map", purpose: "Show coordination stages without inventing a patient story or clinical result.", flow: ["starting point", "records and consent", "hospital review", "travel planning", "follow-up handoff"], channels: ["Instagram", "LinkedIn", "YouTube"], useCases: ["all"] },
  { id: "founder-commentary", name: "Founder Commentary", purpose: "Explain a market observation in a direct, opinion-led voice.", flow: ["contrarian observation", "three reasons", "what changes for families", "principled takeaway"], channels: ["X", "LinkedIn", "Instagram", "YouTube Shorts"], useCases: ["all"] },
  { id: "workflow-demo", name: "Workflow Demo", purpose: "Show how a facilitator organizes research and coordination, not how a clinician treats a patient.", flow: ["big workflow promise", "fast process shots", "quality/safety checks", "handoff", "CTA"], channels: ["Paid", "Organic", "LinkedIn"], useCases: ["all"] },
  { id: "faq-answer", name: "FAQ Answer", purpose: "Answer one high-intent question in plain language and route clinical questions to qualified teams.", flow: ["spoken question", "short answer", "important boundary", "what to ask next"], channels: ["Search", "YouTube", "TikTok", "WhatsApp education"], useCases: ["all"] },
  { id: "carousel-to-short", name: "Carousel to Short", purpose: "Create one source idea, then repurpose it into a video, carousel, static ad and SEO section.", flow: ["source thesis", "five cards", "motion cut", "caption variants", "UTM package"], channels: ["All social", "SEO", "Paid"], useCases: ["all"] },
];

export const factoryWorkflow = [
  "Brief and objective", "Public-web research packet", "Format and storyline selection", "Script and claim-safety review", "Character/style reference creation", "Scene, image, video and audio generation", "Captions, crops and channel variants", "Human approval queue", "Publishing-ready payloads", "Attribution and iteration",
];

export function shortTemplate(id) {
  return shortTemplateCatalog.find((item) => item.id === id) || shortTemplateCatalog[0];
}
